# Use Nginx to serve static files
FROM nginx:alpine

# Copy static frontend files to Nginx's default public directory
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Nginx starts automatically